{
 "title": "Pizza Dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Revenue",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyBTC" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(pizza_revenue_total{service_name=\"jwt-pizza-service\"}[1m]) * 60",
     "legendFormat": "Revenue/min (bitcoin)"
    }
   ]
  },
  {
   "title": "Pizzas",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "rate(pizza_sold_total{service_name=\"jwt-pizza-service\"}[1m]) * 60",
     "legendFormat": "pizzas sold/minute"
    },
    {
     "expr": "rate(pizza_failures_total[1m]) * 60",
     "legendFormat": "Pizzas failed/minute"
    }
   ]
  },
  {
   "title": "Active Users",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "active_users{service_name=\"jwt-pizza-service\"}",
     "legendFormat": "Active Users"
    }
   ]
  },
  {
   "title": "CPU and Memory Usage",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cpu_usage{service_name=\"jwt-pizza-service\"}",
     "legendFormat": "CPU Usage %"
    },
    {
     "expr": "memory_usage{service_name=\"jwt-pizza-service\"}",
     "legendFormat": "Memory Usage %"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "stat",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "service_latency_avg{service_name=\"jwt-pizza-service\"}",
     "legendFormat": "Request Latency (ms)"
    },
    {
     "expr": "pizza_creation_latency_avg{service_name=\"jwt-pizza-service\"}",
     "legendFormat": "Pizza Creation Latency (ms)"
    }
   ]
  },
  {
   "title": "Requests by Method",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "rate(http_requests_get_total{service_name=\"jwt-pizza-service\"}[1m]) * 60",
     "legendFormat": "GET"
    },
    {
     "expr": "rate(http_requests_post_total{service_name=\"jwt-pizza-service\"}[1m]) * 60",
     "legendFormat": "POST"
    },
    {
     "expr": "rate(http_requests_put_total{service_name=\"jwt-pizza-service\"}[1m]) * 60",
     "legendFormat": "PUT"
    },
    {
     "expr": "rate(http_requests_delete_total{service_name=\"jwt-pizza-service\"}[1m]) * 60",
     "legendFormat": "DELETE"
    },
    {
     "expr": "rate(http_requests_total{service_name=\"jwt-pizza-service\"}[1m]) * 60",
     "legendFormat": "Total Requests"
    }
   ]
  },
  {
   "title": "Auth Requests per Minute",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "expr": "rate(auth_success_total{service_name=\"jwt-pizza-service\"}[5m]) * 60",
     "legendFormat": "Successful"
    },
    {
     "expr": "rate(auth_failure_total{service_name=\"jwt-pizza-service\"}[5m]) * 60",
     "legendFormat": "Failed"
    }
   ]
  }
 ]
}